name: Python CI

on:
  - push
  - pull_request

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    environment: task_manager_env

    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pip install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: poetry
      - name: Install dependencies
        run: make install
      - name: Linter check
        run: make lint
      # - name: Run tests
      #   env:
      #     SECRET_KEY: ${{ secrets.SECRET_KEY }}
      #     DATABASE_URL: ${{ secrets.DATABASE_URL }}
      #   run: make test
      - name: Run tests & publish code coverage
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        with:
          coverageCommand: make test-coverage
          coverageLocations: ${{github.workspace}}/*.lcov:lcov
